@echo off
chcp 65001
echo [1/5] 正在爬取現貨資料...
python src/scrapers/爬現貨.py

echo [2/5] 正在爬取期貨資料...
python src/scrapers/爬期貨.py

echo [3/5] 正在進行數據合併與特徵工程...
python src/core/期貨+現貨合併.py

echo [4/5] 正在執行 V8 Stacking 模型預測...
python src/core/預測產出.py

echo [5/5] 正在將狙擊戰報發送到 Discord/LINE...
python src/notifications/0206管理員傳送.py
